### ISSUE TITLE
AsyncAPI 3.0.0 compatibility

### ISSUE THREAD

**Issue by lino** [quarkiverse/quarkus-asyncapi#182]
Hey,

it's been almost half a year since 3.0.0 was released. Since my workplace is discussing the timeline regarding switching to 3.0.0, I'd like to humbly ask, if there are any plans to generate 3.0.0 compliant schemas.

Also I'd gladly offer assistance in implementing this, as I am way too lazy to write our schemas by hand (or migrate them to 3.0.0 compatibility)

Thanks a lot for the time you have been putting into this,
Lino

**Comment by ChMThiel** [comment]
> @fjtirado I will also take a look in the other part of the code. Probably the best approach is that @ChMThiel open a PR in his part (which will fail because of my part) and then I open a PR over that PR for my part (that will be finally green)

@fjtirado see https://github.com/quarkiverse/quarkus-asyncapi/pull/184
